name: Build and publish

on:
  push:
    branches:
    paths:
      - src/**
  pull_request:
    branches:
    paths:
      - src/**

jobs:
  publish:
    name: Build and publish application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7
      
      - name: Restore dependencies
        run: |
          cd src
          dotnet restore
          echo "✅ Project restored"
      
      - name: Build
        run: |
          dotnet build "src/Api/Api.csproj" -c Release -o ./build --no-restore
          echo "✅ Project built"

      - name: Publish
        run: |
          dotnet publish "src/Api/Api.csproj" -c Release -o ./publish --no-restore
          echo "✅ Project published"

#      - name: Upload artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: publish
#          path: ./publish
#
#      - name: Download artifact
#        uses: actions/download-artifact@v3
#        with:
#          name: publish